### ISSUE TITLE
This is not a linear attention transformer.

### ISSUE THREAD

**Issue by iminfine** [OpenNLPLab/TransnormerLLM#10]
In the section 3.2.1 LIGHTNING ATTENTION, you said _As a result, during training, we continue to use the conventional left-multiplication version._  So the computational complexity is still O(n^2d), and given that using the word linear in the main text is not suitable. A softmax free attention might be greater to avoid misunderstanding.

**Comment by Doraemonzzz** [comment]
Thank you for your suggestion. we'll update our paper later. For now, you can take https://arxiv.org/abs/2401.04658 for reference.
