### ISSUE TITLE
configuration for 385M Transformer 

### ISSUE THREAD

**Issue by XintianHan** [OpenNLPLab/TransnormerLLM#6]
Interesting work. 

I have a question on the experiments. I noticed that there is a comparison of Transformer and transnormer at 385M scale. But what's the exact configuration for 385M tranformert? If we use hidden size = 4 x input size, then for input size = 1024, the total number of parameters equals to (1024 * 1024 * 4 + 1024 * 4096 * 2) * 24 = 302M < 385M. Where does the extra parameters go?

**Comment by Doraemonzzz** [comment]
You should also take the parameters of the embedding layer into account.

**Comment by XintianHan** [comment]
> You should also take the parameters of the embedding layer into account.

Thanks. If I take 64000 * 1024 embedding layer into account, the total number of parameters equal to ((1024 * 1024 * 4 + 1024 * 4096 * 2) * 24 + 64000 * 1024) / 1024 / 1024 = 350.5 still less than 385M. Any comment here?

**Comment by Doraemonzzz** [comment]
We provide the following function for calculating the number of parameters:

```python
def compute_params(vocab_size, d, layer, basedim=256):
    # norm linear attention 
    cnt1 = d * d * 5
    # glu
    # glu hidden dim
    e = ((8 * d // 3) + basedim - 1) // basedim * basedim
    cnt2 = 3 * d * e
    
    cnt = vocab_size * d + (cnt1 + cnt2) * layer
    
    return cnt / 1024 / 1024
```
For example, `compute_params(64000, 1024, 24)=380.5`

**Comment by XintianHan** [comment]
> We provide the following function for calculating the number of parameters:
> 
> ```python
> def compute_params(vocab_size, d, layer, basedim=256):
>     # norm linear attention 
>     cnt1 = d * d * 5
>     # glu
>     # glu hidden dim
>     e = ((8 * d // 3) + basedim - 1) // basedim * basedim
>     cnt2 = 3 * d * e
>     
>     cnt = vocab_size * d + (cnt1 + cnt2) * layer
>     
>     return cnt / 1024 / 1024
> ```
> 
> For example, `compute_params(64000, 1024, 24)=380.5`

Hi. Thanks for the instant reply again. I want to point out that my question is on **transformer** not transnormer. You provide a comparison of transformer and transnormer's performance for 385M. I am wondering which hidden size you use for **transformer** and how you get 385M for **transformer**.

**Comment by Doraemonzzz** [comment]
Sorry, I misunderstood the question. The function to calculate the number of parameters for the Transformer is as follows:
```
def compute_params_transformer(vocab_size, d, layer, basedim=256):
    # attention 
    cnt1 = d * d * 4
    # ffn
    e = ((8 * d // 3) + basedim - 1) // basedim * basedim
    cnt2 = 3 * d * e
    
    cnt = vocab_size * d + (cnt1 + cnt2) * layer
    
    return cnt / 1024 / 1024
```
For the transformer model, the number of layers is set to 26, i.e, `compute_params_transformer(64000, 1024, 26)=381`.

**Comment by XintianHan** [comment]
> Sorry, I misunderstood the question. The function to calculate the number of parameters for the Transformer is as follows:
> 
> ```
> def compute_params_transformer(vocab_size, d, layer, basedim=256):
>     # attention 
>     cnt1 = d * d * 4
>     # ffn
>     e = ((8 * d // 3) + basedim - 1) // basedim * basedim
>     cnt2 = 3 * d * e
>     
>     cnt = vocab_size * d + (cnt1 + cnt2) * layer
>     
>     return cnt / 1024 / 1024
> ```
> 
> For the transformer model, the number of layers is set to 26, i.e, `compute_params_transformer(64000, 1024, 26)=381`.

Now I understand. Thank you very much.
