### ISSUE TITLE
你好，请问各个参数量的模型默认加载使用会占用多少显存？不同max_new_tokens大概会要占用多少显存？

### ISSUE THREAD

**Issue by relic-yuexi** [OpenNLPLab/TransnormerLLM#7]
如题所示。我在autodl上使用3090加载7B模型，发现占用超过20GB显存，好像无法开启fp16=True，或者torch_dtype=torch.float16会报nan错误，也就是说半精度无法使用。

>2024-01-10 15:06:11 | INFO | accelerate.utils.modeling | We will use 90% of the memory on device 0 for storing the model, and 10% for the buffer to avoid OOM. You can set `max_memory` in to a higher value to use more memory (at your own risk).

```python
from transformers import AutoModelForCausalLM, AutoTokenizer
import torch

tokenizer = AutoTokenizer.from_pretrained("/root/autodl-tmp/OpenNLPLab/TransNormerLLM2-7B-300B", trust_remote_code=True)
model = AutoModelForCausalLM.from_pretrained("/root/autodl-tmp/OpenNLPLab/TransNormerLLM2-7B-300B", device_map="auto", trust_remote_code=True)

```

```python



def generate_text(input_text: str) -> str:


    
    inputs = tokenizer(input_text, return_tensors='pt').to("cuda")

    
    pred = model.generate(**inputs, max_new_tokens=512, repetition_penalty=1.0)

    
    return tokenizer.decode(pred.cpu()[0], skip_special_tokens=True)


```

这是封装的生成文本代码，`print(generate_text('今天是美好的一天'))` 耗费 4m18.6s
生成内容：
```
今天是美好的一天
2019
02
03
                   
02
03
我 们是华润苏果大家庭
217日华润苏果全体同仁
向所有人问安
2019
03
04
 "undefined"                                        
02
03
                                                         
02
03
04
                    
02
03
                   《我 们  》
02
...

《
 "  "  "  "  "  "  "  "  "  "  "  "  "  "  "  "  "  "  "  "  "  "  "  "  "  "  	
```

```python
prompt = """

请将下面的数据以json的形式返回。

a:b,c:d

下面是格式化的json数据：
```json

"""
```

耗时是4m22.2s的，返回结果如下：
```

请将下面的数据以json的形式返回。

a:b,c:d

下面是格式化的json数据：
```json


		"id":"338",
		"name":"hk"
		"	"		"	//中文名
				"url":"http://jiajunxing.com/" 		//网站地址
				"des":"首页"			//首页描述
				"img":"http://jiajunxing/.			 //首页图片
				"status":"100000000"			 //状态：1-测试 2-可用		//正常或异常
				"page":"1"				//总页数
				"			//	}			//						//返回结果
*/			"id":39,			//"id":39,				//		(id = json数据的id，可选，不能设置)		//			返回结果数据id：39)			//	39 = 普通版，34 = 优化版，39/1 = 优化版	//		(普通版和优化版，可选，不能设置)
				//			"category":[39,34]			//		//									(普通版和优化版的默认，可选)		//					//						//		//				//				//				//					//						//					//		//		//		//		//		////////////////////// //		
				"											 return										           														        					                  //				      "  			   "
```

我还以为是3090太差了，所以也测试了chatglm3-6B，使用相同语句，只改了模型路径的情况下。

加载占用显存12GB左右。

第一个推理5.7s，下面是返回结果

```
[gMASK]sop 今天是美好的一天
今天是美好的一天,阳光明媚,空气清新,心情愉悦。在这样的日子里,我感到非常幸福和满足。

我早早地起床,做了一些晨练,让自己保持健康和活力。之后,我享用了一顿美味的早餐,与家人一起度过了一个温馨的早晨。

上午,我参加了一个重要的会议,与同事们一起讨论和解决了一些关键问题。我很高兴能够为团队做出贡献,并从中学到了很多。

中午,我和同事们一起吃了午餐,享受了一个轻松愉快的午餐时光。

下午,我继续工作,处理了一些重要的任务。同时,我也抽出时间与一些朋友进行了联系,与他们分享了自己的生活和想法。

傍晚,我参加了一个社交活动,与朋友们一起度过了愉快的时光。

晚上,我回家与家人共进晚餐,享受了一个温馨的家庭夜晚。

今天是美好的一天,我感到非常幸福和满足。我希望未来的日子里,能够继续保持这样的好心情和美好的生活。

```
第二个推理0.5s，下面是返回结果：

```
[gMASK]sop 

请将下面的数据以json的形式返回。

a:b,c:d

下面是格式化的json数据：
```json

{
  "a": "b",
  "c": "d"
}
```
```

就目前的体验来看，并没有感觉到TransnormerLLM的优势所在，甚至感觉消耗更大了，不知道作者团队是否有相关的测试，在什么情况下，这个模型的实用性会更好。

**Comment by XuyangShen** [comment]
我们正在复现问题，请耐心等待一下！谢谢

**Comment by XuyangShen** [comment]
**对于您上述提到的`FP16 nan`的问题，经过我们的测试：**


- 我们复现了您提到的`FP16 nan`的问题:  
```bash
>>>AutoModelForCausalLM.from_pretrained("TransNormerLLM2-7B-300B", torch_dtype=torch.float16, device_map="auto", trust_remote_code=True)
>>>inputs = tokenizer('今天是美好的一天', return_tensors='pt').to('cuda')
>>>pred = model.generate(**inputs, max_new_tokens=512, repetition_penalty=1.0)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mnt/workspace/shenxuyang/miniconda3/envs/hf/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/mnt/workspace/shenxuyang/miniconda3/envs/hf/lib/python3.10/site-packages/transformers/generation/utils.py", line 1764, in generate
    return self.sample(
  File "/mnt/workspace/shenxuyang/miniconda3/envs/hf/lib/python3.10/site-packages/transformers/generation/utils.py", line 2897, in sample
    next_tokens = torch.multinomial(probs, num_samples=1).squeeze(1)
RuntimeError: probability tensor contains either `inf`, `nan` or element < 0
```

- `TransNormerLLM`系列模型在使用中，建议使用`BF16`，3090经过我们的测试也支持该数据的格式，您也可以参考这篇文章https://discuss.pytorch.org/t/bfloat16-native-support/117155。
```python
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("TransNormerLLM2-7B-300B", trust_remote_code=True)
model = AutoModelForCausalLM.from_pretrained("TransNormerLLM2-7B-300B", torch_dtype=torch.bfloat16, device_map="auto", trust_remote_code=True)
inputs = tokenizer('今天是美好的一天', return_tensors='pt').to('cuda')
pred = model.generate(**inputs, max_new_tokens=512, repetition_penalty=1.0)
print(tokenizer.decode(pred.cpu()[0], skip_special_tokens=True))
```
在通过`AutoModelForCausalLM`加载模型的是时候，需要指定`torch_dtype=torch.bfloat16`。您可以通过上述python代码再次尝试。我们也会及时更新HF对`BF16`的说明。


**对于您上述提到的显存的问题，经过我们的测试：**

-在上述`bf16`的setting下，加载和推理`TransNormerLLM2-7B-300B`需要`16GB`的显存 (bsz=1)，以下是显卡状态的截图
<img width="1976" alt="截屏2024-01-11 14 56 38" src="https://github.com/OpenNLPLab/TransnormerLLM/assets/37824565/4fb36574-7a29-4270-a907-79c5277dc4a1">

- 我们也将稍后更新速度和显存与主流transformer架构大语言模型的对比。

**对于您上述提到推理结果的问题，经过我们的测试：**

- `TransNormerLLM2-7B-300B` 目前是预训练基座模型，即只经过预训练，没有经过chat, agent, code, alignment等微调和对齐，且预训练数据为300B数据。由于上述两个原因，其生成结果和指令的响应还不能与主流的chat大语言模型对比。您可以通过我们repo中 [fine-tune]('https://github.com/OpenNLPLab/TransnormerLLM/tree/main/fine-tune')微调一个chat版本模型，可能会更加适合您想要的场景。

- 我们也通过上述python代码做了一个generation的样例，请参考（由于temperature，每次结果会有差异）
```bash
>>> inputs = tokenizer('今天是美好的一天', return_tensors='pt').to('cuda')
>>> pred = model.generate(**inputs, max_new_tokens=512, repetition_penalty=1.0)
>>> print(tokenizer.decode(pred.cpu()[0], skip_special_tokens=True))
今天是美好的一天，也是和小伙伴们一起努力的日子，让我们共同珍惜这一天吧！
明天是崭新的一天，也是小伙伴们和爸爸妈妈一起努力的第一天，让我们共同期待吧！
今天是美妙的一天，也是小伙伴们一起进步的一天，让我们共同期待吧！
感谢今天陪我的老师们
感谢老师们陪伴
有你们真好！


>>> inputs = tokenizer('今天是美好的一天', return_tensors='pt').to('cuda')
>>> pred = model.generate(**inputs, max_new_tokens=512, repetition_penalty=1.0)
>>> print(tokenizer.decode(pred.cpu()[0], skip_special_tokens=True))
今天是美好的一天，感谢你用青春和鲜血染红了祖国的河山，愿你在祖国的河山上放歌华夏，愿你在民族的文化中激荡青春，愿你在人生百年的征途中续写华章，祝福你！在祖国母亲七十岁的生日来临之际，希望你能与祖国共成长，与时代共进步！祝福祖国明天更美好！】
1081《最可爱的中国》
“......你从五千年的悠久历史中走来，
我从亿万人民中来;
在五千年的发展进步中，
我使中华民族，不断得到加强补充。
让世界走进一个繁荣富强的新中国，
使世界充满爱戴和敬仰！”
《我爱你中国》一曲雄伟壮美的《国歌》，将这首歌曲的深厚底蕴和气势一一展现出来，而在这首歌曲中，
最引人注目的，莫过于那雄浑古朴的歌词了，作者是毛泽东，其作词的背景是祖国解放的大业和抗美援朝战争的胜利，以及新中国成立的喜悦和幸福。他通过这样的笔触，真实形象地描述了祖国的美丽繁荣面貌，并充分体现了中国各族人民坚韧而勇敢的革命精神和自强不息的精神面貌，使歌曲达到高潮。
《义勇军进行曲》
最年轻的军官，
最可爱的儿童，
最光辉的中国战士;
```

**Comment by XuyangShen** [comment]
**非常感谢您对TransNormerLLM的关注**

### **数据混乱和实际体验效果问题**

- 借用您提到的`chatglm3-6B-base`中提到的一句话，”基座模型是作为没有经过人类意图对齐的模型，ChatGLM3-6B-Base 不能用于多轮对话。但是可以进行文本续写”。 因此在temperature的影响下，模型对于输入的文字的续写是随机的。从推理生成的结果是无法反推训练数据的样本是否混乱。对于模型生成temperature的讨论，您可以参考[https://discuss.huggingface.co/t/what-is-temperature/11924](https://discuss.huggingface.co/t/what-is-temperature/11924)这里面提到的进行尝试。

- [https://huggingface.co/OpenNLPLab/TransNormerLLM2-7B-300B#benchmark-results](https://huggingface.co/OpenNLPLab/TransNormerLLM2-7B-300B#benchmark-results)我们在模型的发布页面上，对`TransNormerLLM2-7B` `300Btokens` 版本进行了评测，我们也在表中展示了`chatglm2-6B`的评测结果。简单对比看，300B Token的`TransNormerLLM2-7B`相较于训练了1400B Tokens 的`chatglm2-6B`是有一定的差距。我们应该在相同数量训练Tokens下，进行比较才有说服力。`TransNormerLLM2-7B-300B`与同样训练了300B tokens的`pythia`和`opt`是具有竞争力的。可以期待一下7B模型的完整版！

- 我们的评测框架都是基于开源的[lm-evalutaion-harness](https://github.com/EleutherAI/lm-evaluation-harness)进行评测。您可以复现`TransNormerLLM2-7B-300B`的评测结果，也可以对`chatglm3-6B-base`进行评测。


### **TransNormerLLM模型推理速度**

- 我们对于`Lightning Attention-1`的`TransNormerLLM-7B`进行了吞吐推理测试（我们的测试平台采用了开源[的vllm hf-backend)](https://github.com/vllm-project/vllm/blob/main/benchmarks/benchmark_throughput.py)。以下是测试结果：

<img width="666" alt="截屏2024-01-11 21 14 24" src="https://github.com/OpenNLPLab/TransnormerLLM/assets/37824565/efa617cb-82ad-4460-9c43-119dd630ecf3">
<img width="666" alt="截屏2024-01-11 21 14 30" src="https://github.com/OpenNLPLab/TransnormerLLM/assets/37824565/ba93e96d-6bf2-4660-adc9-a09d30d2c04f">

我们的测试平台是单卡A100-80G，评测数据集为`ShareGPT_V3_unfiltered_cleaned_split.json`。

通过吞吐推理测试，可以发现**我们模型的表现是`chatglm2-6B`和`chatglm3-6B`的3.5倍。** （您上述提到的超过4m的推理时间，请确认是否在cpu上进行了推理以及是否正确安装了triton等环境依赖包）

### **Lightning Attention-2的新模型**

- 感谢您对`Lightning Attention-2`技术的关注。我们已经发布的`TransNormerLLM`系列所有模型，都可以直接无任何训练成本升级到`Lightning Attention-2`，以及享受`Lightning Attention-2`所有的优势。我们也会在近期对已经发布的`TransNormerLLM`系列所有模型加上`Lightning Attention-2`的选择。

- 同时，`TransNormerLLM3-15B`模型从预训练开始就原生支持了`Lightning Attention-2`，现已经对第一个50Btoken开源了，您可以通过[https://huggingface.co/OpenNLPLab/TransNormerLLM3-15B-Intermediate-Checkpoints](https://huggingface.co/OpenNLPLab/TransNormerLLM3-15B-Intermediate-Checkpoints)访问权重。

**Comment by relic-yuexi** [comment]
对于我说的数据混乱问题，我向您道歉，如果是其他机构如openai，文心等等我也会指出这个问题，可能言语有些过激，但对于自己国家的国歌被篡改这种事我觉得我说的数据混乱这个问题也没有错误，但还是专注于学术比较好。

下面是使用rtx4090的，未使用bf16，相关的包以及代码以及显存占用都在图上了，我们现在是在发现问题，比如说如果是在cpu上推理了，是为什么会这样，那么代码一样的情况下，推理时gpu显存也有波动，你也可以检查代码是否有误。

![image](https://github.com/OpenNLPLab/TransnormerLLM/assets/53668275/94c54b83-e703-44c5-9b9b-436c8b306cef)


![image](https://github.com/OpenNLPLab/TransnormerLLM/assets/53668275/7b1efc00-e31a-42b0-949a-8238f0f5a40e)

![image](https://github.com/OpenNLPLab/TransnormerLLM/assets/53668275/b7c8c3f4-27db-47b7-ae88-abd3068f2843)

![image](https://github.com/OpenNLPLab/TransnormerLLM/assets/53668275/c4a5e49a-303b-43c7-997a-3b60ddb7bea2)

![image](https://github.com/OpenNLPLab/TransnormerLLM/assets/53668275/39e50dc8-5973-43d7-ab9f-131a2007f169)

![image](https://github.com/OpenNLPLab/TransnormerLLM/assets/53668275/c612536d-36a9-45a1-90a3-9512a10f60bc)

![image](https://github.com/OpenNLPLab/TransnormerLLM/assets/53668275/de7a3096-b553-4319-829b-df670d89e2f3)

运行时的GPU变化。

同时为了避免你说的随机性，我将使用贪婪方式生成，理论上这样消耗的时间就是生成max_new_tokens=512所耗的时间，看如下代码：

`num_beams` 是用于控制模型生成文本时的束搜索（beam search）大小的参数。束搜索是一种在生成文本时用于平衡速度和质量的策略。

![image](https://github.com/OpenNLPLab/TransnormerLLM/assets/53668275/f95bde46-050d-420a-805e-7d32afd28d44)

下面是运行结果

![image](https://github.com/OpenNLPLab/TransnormerLLM/assets/53668275/9a27a419-d68f-491b-8c82-0fe4215121cf)

**Comment by OpenNLPLab123** [comment]
由于之前涉及敏感信息，我们将修改部分内容。对于生成混乱的问题，应该是bf-16带来的。另一方面，我们将：

1. 测评chatglm3；
2. 修复推理测bug；

再次感谢您对模型的关注。

**Comment by ChuanhongLi** [comment]
> **非常感谢您对TransNormerLLM的关注**
> 
> ### **数据混乱和实际体验效果问题**
> * 借用您提到的`chatglm3-6B-base`中提到的一句话，”基座模型是作为没有经过人类意图对齐的模型，ChatGLM3-6B-Base 不能用于多轮对话。但是可以进行文本续写”。 因此在temperature的影响下，模型对于输入的文字的续写是随机的。从推理生成的结果是无法反推训练数据的样本是否混乱。对于模型生成temperature的讨论，您可以参考https://discuss.huggingface.co/t/what-is-temperature/11924这里面提到的进行尝试。
> * https://huggingface.co/OpenNLPLab/TransNormerLLM2-7B-300B#benchmark-results我们在模型的发布页面上，对`TransNormerLLM2-7B` `300Btokens` 版本进行了评测，我们也在表中展示了`chatglm2-6B`的评测结果。简单对比看，300B Token的`TransNormerLLM2-7B`相较于训练了1400B Tokens 的`chatglm2-6B`是有一定的差距。我们应该在相同数量训练Tokens下，进行比较才有说服力。`TransNormerLLM2-7B-300B`与同样训练了300B tokens的`pythia`和`opt`是具有竞争力的。可以期待一下7B模型的完整版！
> * 我们的评测框架都是基于开源的[lm-evalutaion-harness](https://github.com/EleutherAI/lm-evaluation-harness)进行评测。您可以复现`TransNormerLLM2-7B-300B`的评测结果，也可以对`chatglm3-6B-base`进行评测。
> 
> ### **TransNormerLLM模型推理速度**
> * 我们对于`Lightning Attention-1`的`TransNormerLLM-7B`进行了吞吐推理测试（我们的测试平台采用了开源[的vllm hf-backend)](https://github.com/vllm-project/vllm/blob/main/benchmarks/benchmark_throughput.py)。以下是测试结果：
> 
> <img alt="截屏2024-01-11 21 14 24" width="666" src="https://private-user-images.githubusercontent.com/37824565/295925393-efa617cb-82ad-4460-9c43-119dd630ecf3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU4OTA0MDAsIm5iZiI6MTcwNTg5MDEwMCwicGF0aCI6Ii8zNzgyNDU2NS8yOTU5MjUzOTMtZWZhNjE3Y2ItODJhZC00NDYwLTljNDMtMTE5ZGQ2MzBlY2YzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIyVDAyMjE0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlmNWViZTFiYzc0NmZlNGEzZmRiZTA4ZTMyYWJkZjdhZGExZmMyOWU5Y2M2YmNjNjAzZjU4ZGEwMzM2MzU3NTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Z_hW8b4pfuGqzZE0UD_IeKNZg9OhSSJ84tqKNBhBMCc"> <img alt="截屏2024-01-11 21 14 30" width="666" src="https://private-user-images.githubusercontent.com/37824565/295925411-ba93e96d-6bf2-4660-adc9-a09d30d2c04f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU4OTA0MDAsIm5iZiI6MTcwNTg5MDEwMCwicGF0aCI6Ii8zNzgyNDU2NS8yOTU5MjU0MTEtYmE5M2U5NmQtNmJmMi00NjYwLWFkYzktYTA5ZDMwZDJjMDRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIyVDAyMjE0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYxNzgyYTEwODMyNzViNDk3MTQ3NjBjYzA1YzA2YjM5NDk3NzA0NTQ3Y2QzYjdhN2E3ZjgyNWUyNzUzNjFjN2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Osysrc-IRNGXBwOP83DFEONQs7YHc042OsGZkX0FE4Y">
> 我们的测试平台是单卡A100-80G，评测数据集为`ShareGPT_V3_unfiltered_cleaned_split.json`。
> 
> 通过吞吐推理测试，可以发现**我们模型的表现是`chatglm2-6B`和`chatglm3-6B`的3.5倍。** （您上述提到的超过4m的推理时间，请确认是否在cpu上进行了推理以及是否正确安装了triton等环境依赖包）
> 
> ### **Lightning Attention-2的新模型**
> * 感谢您对`Lightning Attention-2`技术的关注。我们已经发布的`TransNormerLLM`系列所有模型，都可以直接无任何训练成本升级到`Lightning Attention-2`，以及享受`Lightning Attention-2`所有的优势。我们也会在近期对已经发布的`TransNormerLLM`系列所有模型加上`Lightning Attention-2`的选择。
> * 同时，`TransNormerLLM3-15B`模型从预训练开始就原生支持了`Lightning Attention-2`，现已经对第一个50Btoken开源了，您可以通过https://huggingface.co/OpenNLPLab/TransNormerLLM3-15B-Intermediate-Checkpoints访问权重。

@XuyangShen  您好，请问下 -- 我们的测试平台采用了开源[的vllm hf-backend)](https://github.com/vllm-project/vllm/blob/main/benchmarks/benchmark_throughput.py) 这个测试脚本的运行参数配置可以分享一下不？

**Comment by XuyangShen** [comment]
您好，以下是我们的测试脚本和配置，请参考

```python
# 在benchmark_throughput.py 中您需要更改更新如下代码

llm = AutoModelForCausalLM.from_pretrained(model, torch_dtype=torch.bfloat16, trust_remote_code=trust_remote_code)
llm.eval()

llm.config.pad_token_id = 0
tokenizer.pad_token_id = 0
```

```bash

export use_triton=True
export debug=True

for bs in 10
do
    python3 benchmark_throughput.py \
        --backend hf \
        --dataset ShareGPT_V3_unfiltered_cleaned_split.json \
        --model OpenNLPLab/TransNormerLLM-7B \
        --tokenizer OpenNLPLab/TransNormerLLM-7B \
        --hf-max-batch-size $bs \
        --trust-remote-code \
        --dtype bfloat16 \
        2>&1 | tee logs/TNL7B-bs$bs-triton.log
done

```

如果您想测试用纯torch版本，请将上述`export use_triton=Fasle`。

我们在上述测试的模型为TNL1-7B: https://huggingface.co/OpenNLPLab/TransNormerLLM-7B
由于TNL2-7B, 和 TNL3-15B 还处在开发预训练阶段，我们还没测试其推理吞吐量。
